### ISSUE TITLE
Notifications on new Youtube videos

### ISSUE THREAD

**Issue by denzelby** [denzelby/telegram-bot-bumblebee#12]
Only for "subscribed" channels

**Comment by nchereva** [comment]
Nice feature 👍 , but again who will manage subscription, will be subscription depends on channel name or will be global, also what with storage?

**Comment by denzelby** [comment]
Subscribe dynamically via:
/youtube sub <channel id or some>
So everyone can add channels. Scheduled job can be implemented to check for updates. Ideally it should be done via push notifications from youtube itself, but I don't think there is an API for this available.

Regarding storage: already have postgresql behind (access via spring-data, so we can switch to pretty much anything). More than enough for now.
